project:
  type: website

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

website:
  google-analytics: "G-Z003ZL327P"
  twitter-card: true
  open-graph: true
  favicon: 'images/logo.png'
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
        - text: 'Computational Research Tools'
          file: install.ipynb
        - text: 'Supreme (AI) Transcripts'
          file: scc/index.qmd
    right:
        - text: 'Blog'
          href: blog/index.qmd
        - text: 'About'
          file: about.ipynb
        - icon: twitter
          href: https://twitter.com/simonwallace/
  sidebar:
    - contents:
        - install.ipynb
        - 00_CanLii.ipynb
        - 01_wgnd.ipynb


  page-footer: 
    left: "Simon Wallace (2022)" 
    right: 
      - icon: github
        href: https://github.com/simon-lawyer/
      - icon: twitter 
        href: https://twitter.com/simonwallace/    

metadata-files: [nbdev.yml]